# Generated by Django 3.2.20 on 2023-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(default=None, null=True)),
                ('intensity', models.IntegerField(default=None, null=True)),
                ('sector', models.CharField(default=None, max_length=20, null=True)),
                ('topic', models.CharField(default=None, max_length=20, null=True)),
                ('insight', models.CharField(default=None, max_length=250, null=True)),
                ('url', models.CharField(default=None, max_length=250, null=True)),
                ('region', models.CharField(default=None, max_length=50, null=True)),
                ('start_year', models.IntegerField(default=None, null=True)),
                ('impact', models.IntegerField(default=None, null=True)),
                ('added', models.DateTimeField(default=None, null=True)),
                ('published', models.DateTimeField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('relevance', models.IntegerField(default=None, null=True)),
                ('pestle', models.CharField(default=None, max_length=50, null=True)),
                ('source', models.CharField(default=None, max_length=50, null=True)),
                ('title', models.CharField(default=None, max_length=250, null=True)),
                ('likelihood', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
