# Generated by Django 3.2.4 on 2023-11-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('hastag', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('tweets', models.TextField(null=True)),
                ('sentiment', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
